steps:
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  args:
  - gcloud
  - functions
  - deploy
  - function-go
  - --region=us-central1
  - --source=cmd/scraper-go
  - --trigger-http
  - --runtime=go120