-- Variations
CREATE TABLE product_attributes (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,  -- for pg 10+
    product_id bigint NOT NULL,
    attribute_id bigint,
    variation_id text,
    sku text,
    date_added timestamp NOT NULL,
    date_updated timestamp NOT NULL,
    CONSTRAINT u_constraint UNIQUE (product_id, attribute_id, variation_id, sku)
);
