CREATE TABLE variation_attributes (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,  -- for pg 10+
    variation_id int NOT NULL,
    attribute_id int NOT NULL,
    date_added timestamp NOT NULL,
    date_updated timestamp NOT NULL
);