CREATE TABLE attributes (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,  -- for pg 10+
    attribute_name text NOT NULL,
    store_id bigint NOT NULL,
    date_added timestamp NOT NULL,
    date_updated timestamp
);
