CREATE TABLE datapoints (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,  -- for pg 10+
    product_attr_id bigint NOT NULL,
    stock numeric NOT NULL,
    price integer NOT NULL,
    date_added timestamp NOT null unique
);
