CREATE TABLE product_attributes (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,  -- for pg 10+
    product_id bigint not null,
    attribute_id int,
    attribute_value text,
    variation_id_raw text,
    sku text,
    date_added timestamp NOT NULL,
    date_updated timestamp,
    CONSTRAINT u_constraint UNIQUE (product_id, attribute_id, variation_id_raw, sku)
);