CREATE TABLE products (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,  -- for pg 10+
    product_name text NOT NULL,
    url text not null unique,
    store bigint NOT NULL,
    date_added timestamp NOT NULL,
    date_updated timestamp
);
