CREATE TABLE stores (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,  -- for pg 10+
    store_name text NOT NULL unique,
    url text NOT NULL unique,
    date_added timestamp NOT NULL,
    date_updated timestamp
);
