CREATE TABLE tags (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,  -- for pg 10+
    tag_name text NOT NULL,
    url text unique,
    store bigint NOT NULL,
    date_added timestamp NOT NULL,
    date_updated timestamp
);
